Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
sklearn.datasets.

Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
sklearn.datasets.

Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
cross-validation on load_iris dataset in sklearn.datasets.

Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
sklearn.datasets.

Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
load_iris dataset in sklearn.datasets.

Q6. Implement a function to standardise the features before applying KNN classifier.

Q7. Write a Python function to calculate the euclidean distance between two points.

Q8. Write a Python function to calculate the manhattan distance between two points.

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns


In [8]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,r2_score,mean_absolute_error
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor


In [14]:
#Q1 Implememnt KNN for the Iris Dtaset
iris = load_iris()
x,y = iris.data,iris.target
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)
clssi = KNeighborsClassifier(n_neighbors=5,algorithm='auto')
clssi.fit(x_train,y_train)
ypre = clssi.predict(x_test)
print(accuracy_score(y_test,ypre))
print(confusion_matrix(y_test,ypre))


0.98
[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]


In [16]:
# the optimal value of K for the KNN classifier algorithm using cross-validation
parameter = {
    'n_neighbors':[1,2,3,4,5,6,7],
    'weights':['uniform','distance'],
    'algorithm':['auto','kd_tree','ball_tree']
}
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=clssi,param_grid=parameter,cv=5)
grid.fit(x_train,y_train)
grid.best_params_

{'algorithm': 'auto', 'n_neighbors': 1, 'weights': 'uniform'}

In [18]:
# Q5: KNN Classifier with weighted voting
knn_weighted = KNeighborsClassifier(n_neighbors=3, weights='distance')
knn_weighted.fit(x_train, y_train)
print("KNN Classifier with weighted voting accuracy:", knn_weighted.score(x_test, y_test))



KNN Classifier with weighted voting accuracy: 0.98


In [28]:
# Q7 Write a Python function to calculate the euclidean distance between two points
a1 = [1,2,3]
a2 = [4,5,6]
def euclidean_distance(a1,a2):
  return np.sqrt(np.sum((np.array(a1)-np.array(a2))**2))
print('euclidean_distance:',euclidean_distance(a1,a2))



euclidean_distance: 5.196152422706632


In [30]:
# Q8. Write a Python function to calculate the manhattan distance between two points.
def manhattan_distance(a1,a2):
  return np.sum(abs(np.array(a1)-np.array(a2)))
print('manhattan_distance:',manhattan_distance(a1,a2))

manhattan_distance: 9
